version: "3.8"
services:
    lubank_app:
        container_name: lunbank_demo
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        expose:
            - 9000
        volumes:
            - .:/usr/src/app
            - ./public:/usr/src/app/public
        depends_on:
            - lubank_db
        networks:
            - app_network

    lubank_ngix:
        container_name: lubank_ngix
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./public:/usr/src/app/public
        ports:
            - "8000:80"
        depends_on:
            - lubank_app
        environment:
            NGINX_FPM_HOST: lubank_app
            NGINX_ROOT: /usr/src/app/public
        networks:
            - app_network

    lubank_db:
        container_name: lubank_db
        image: mysql:8.0.20
        restart: always
        volumes:
            - ./storage/db-data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: lubank
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - app_network

    blog_redis:
        container_name: blog_redis
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
